default:
    mongodb:
        url: "mongodb://yoururl"
    log: 
        level: "debug"
    server: 
        port: 6002
    passport:
        rules:
            - url: "/user/**" 
              role: "user"
            - url: "/task/**"
              role: "user"
            - url: "/admin/api/**" 
              role: "admin"
development:
test:
production:
    log: 
        level: "warn"